### ISSUE TITLE
The is not allwinner a23. That is allwinner h3.

### ISSUE THREAD

**Issue by exkc** [Dr-Noob/cpufetch#173]
![Screenshot_20230120-113439_Termux](https://user-images.githubusercontent.com/70055899/213612213-abe0d462-3c33-48c1-b006-c1d95ac5064d.png)

**Comment by Dr-Noob** [comment]
You are right - but I also need the output of `cat /proc/cpuinfo` to fix it.

**Comment by mdoksa76** [comment]
In my case with Orange Pi zero LTS, cpu is Allwinner H2+. It is also detected as A23.

[Mon Jan 30 16:58:04 (39°C) mario@opi-zero:~] <?> cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : Allwinner sun8i Family
Revision        : 0000
Serial          : 02c00142451137ee

**Comment by Dr-Noob** [comment]
Allwinner detection is broken right now. Actually, for your CPU @mdoksa76 cpufetch will unlikely detect it is a H2+ because /proc/cpuinfo does not contain enough information to conclude it. As you can see in the [sunxi wiki](https://linux-sunxi.org/Allwinner_SoC_Family#2013_naming_scheme_change), `sun8i` may belong to many different chips.

I'd appreciate if you guys could search for `sun8iw7p1`, `sun8iw7` or `1680` since any of these in any file in your system would be enough to help detection of the chip. I guess you won't find anything - in that case I'll just fix the program and in the case there is not enough info it will simply print 'Unknown'.

**Comment by mdoksa76** [comment]
Maybe it is better to put Allwinner 8i familly (like neofetch) or Allwinner
ARMv7 rev 5 (v7l) (like screenfetch or inxi -C).

uto, 31. sij 2023. u 20:12 Dr-Noob ***@***.***> napisao je:

**Comment by mdoksa76** [comment]
From https://linux-sunxi.org/H3:
"Variants

H2+ is a variant of H3, targeted at low-end OTT boxes, which lacks Gigabit MAC and 4K HDMI output support.

H3 images are proven to run on H2+.

According to the source code of BSP[[1]](https://linux-sunxi.org/H3#cite_note-1), variants differ by the last byte of the first word of SID. 0x42 and 0x83 indicates H2+, 0x00 and 0x81 indicates H3, and 0x58 indicates H3D (a still unknown variant)."


[Tue Jan 31 22:43:18 (37°C) mario@opi-zero:/etc] <?> hexdump -C /sys/bus/nvmem/devices/sunxi-sid0/nvmem
00000000  42 01 c0 02 20 46 20 15  24 00 97 78 d3 02 29 40  |B... F .$..x..)@|
00000010  59 00 00 02 00 00 00 00  00 00 00 00 00 00 00 00  |Y...............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 0e 08 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100

**Comment by Dr-Noob** [comment]
> From https://linux-sunxi.org/H3: "Variants
> 
> H2+ is a variant of H3, targeted at low-end OTT boxes, which lacks Gigabit MAC and 4K HDMI output support.
> 
> H3 images are proven to run on H2+.
> 
> According to the source code of BSP[[1]](https://linux-sunxi.org/H3#cite_note-1), variants differ by the last byte of the first word of SID. 0x42 and 0x83 indicates H2+, 0x00 and 0x81 indicates H3, and 0x58 indicates H3D (a still unknown variant)."
> 
> [Tue Jan 31 22:43:18 (37°C) mario@opi-zero:/etc] <?> hexdump -C /sys/bus/nvmem/devices/sunxi-sid0/nvmem 00000000 42 01 c0 02 20 46 20 15 24 00 97 78 d3 02 29 40 |B... F .$..x..)@| 00000010 59 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 |Y...............| 00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................| 00000030 00 00 00 00 0e 08 00 00 00 00 00 00 00 00 00 00 |................| 00000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................| * 00000100

That is very promising! I found [this webpage](https://linux-sunxi.org/SID_Register_Guide#Currently_known_SID.27s) which has a list of SIDs. However, your SID dump does not match any of the page. According to the table, your SID should start with `02004620` or `02c00042`. Do you know what's going on?

**Comment by Dr-Noob** [comment]
@exkc Can you post the output of `hexdump -C /sys/bus/nvmem/devices/sunxi-sid0/nvmem`? Maybe it can give us some valuable pieces of information.

**Comment by Dr-Noob** [comment]
> From https://linux-sunxi.org/H3: "Variants
> 
> H2+ is a variant of H3, targeted at low-end OTT boxes, which lacks Gigabit MAC and 4K HDMI output support.
> 
> H3 images are proven to run on H2+.
> 
> According to the source code of BSP[[1]](https://linux-sunxi.org/H3#cite_note-1), variants differ by the last byte of the first word of SID. 0x42 and 0x83 indicates H2+, 0x00 and 0x81 indicates H3, and 0x58 indicates H3D (a still unknown variant)."
> 
> [Tue Jan 31 22:43:18 (37°C) mario@opi-zero:/etc] <?> hexdump -C /sys/bus/nvmem/devices/sunxi-sid0/nvmem 00000000 42 01 c0 02 20 46 20 15 24 00 97 78 d3 02 29 40 |B... F .$..x..)@| 00000010 59 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 |Y...............| 00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................| 00000030 00 00 00 00 0e 08 00 00 00 00 00 00 00 00 00 00 |................| 00000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................| * 00000100

Also interesting to see the output of `devmem2`. Can you guys run?:

```
d0=`./devmem2 0x01c14200 w|grep Value|sed 's/^.*: 0x/ /'`
d1=`./devmem2 0x01c14204 w|grep Value|sed 's/^.*: 0x/ /'`
d2=`./devmem2 0x01c14208 w|grep Value|sed 's/^.*: 0x/ /'`
d3=`./devmem2 0x01c1420c w|grep Value|sed 's/^.*: 0x/ /'`
echo $d0 $d1 $d2 $d3
```

**Comment by mdoksa76** [comment]
My "echo $d0 $d1 $d2 $d3":
2C00142 15204620 78970024 402902D3

I don´t know why those SIDs are different than those on SID Register Guide.

**Comment by Dr-Noob** [comment]
Damn it, looks like an endianness problem. 

From your hexdump command we have `42 01 c0 02` which reversed would be `02c00142` which is what `devmem2` is reporting. And, as you said, "_variants differ by the last byte of the first word of SID. 0x42 and 0x83 indicates H2+, 0x00 and 0x81 indicates H3_" so if we take the last byte in your case it would be 0x42, which indeed indicates an H2+.

Looks like it is a good way of differentiating chips when cpuinfo does not give enough information. I'd appreciate if @exkc could paste the output of the same commands to confirm this - but it looks promising.

**Comment by mdoksa76** [comment]
I have one more Orange Pi Zero LTS (not sure is it H2+ or H3 and it is inside plastic box, so I can`t check.).
devmem2 for this SBC gives output:
2C00042 35904620 7891C31C 5C1F0C93

**Comment by exkc** [comment]
![Uploading Screenshot_20230213-071544_Termux.png…]()

**Comment by exkc** [comment]
![Screenshot_20230213-071544_Termux](https://user-images.githubusercontent.com/70055899/218343178-ceec81b3-26da-4a7e-ae08-5b195fba0243.png)

**Comment by exkc** [comment]
![Screenshot_20230213-071853_Termux](https://user-images.githubusercontent.com/70055899/218343291-a7ebcbd3-045d-4ea8-9838-5eb2f760a0a3.png)

**Comment by exkc** [comment]
Oh btw i have a h6 based sbc. Do  u want me to run those command on ny h6 based sbc/

**Comment by mdoksa76** [comment]
devmem2 output from my Orange Pi Lite (H3 CPU):
2C00081 35D04620 7894C220 183C0793

**Comment by mdoksa76** [comment]
[Mon Feb 13 22:13:59 (39°C) mario@opi-zero:/sys/bus/nvmem/devices/sunxi-sid0] <?> cat uevent
OF_NAME=eeprom
OF_FULLNAME=/soc/eeprom@1c14000
OF_COMPATIBLE_0=allwinner,sun8i-h3-sid
OF_COMPATIBLE_N=1

**Comment by mdoksa76** [comment]
If you wish I can give you ssh access with root credentials to my opi-zero.

**Comment by Dr-Noob** [comment]
> If you wish I can give you ssh access with root credentials to my opi-zero.

That would be very helfpul! Altough I think I wouldn't need root access, a normal user should be fine to take a look under `/sys` and also try some programs from [linux-sunxi](https://github.com/linux-sunxi/sunxi-tools).

Please send me an e-mail to peibolms @ gmail dot com with the information if you are ok with it :+1:

**Comment by mdoksa76** [comment]
I have sent you mail with IP, user and pass.

**Comment by exkc** [comment]
allwinner d1-h 

![image](https://user-images.githubusercontent.com/70055899/218785107-db8e5d45-165d-41bb-a56e-d099190cbcb0.png)


hope it is not too out of topic

**Comment by exkc** [comment]
allwiner h6


![image](https://user-images.githubusercontent.com/70055899/218786944-76753440-7ac9-40f9-b9ef-a9c490f4ca43.png)
 
/sys/bus/nvmem/devices/sunxi-sid0/nvmem is missing :(

**Comment by Dr-Noob** [comment]
> I have sent you mail with IP, user and pass.

Thanks! I'll try to connect this weekend to have a look

**Comment by Dr-Noob** [comment]
Hey, this isn't completed yet. I'm working on a solution - I'll post it in the upcoming days for you guys to test it.

**Comment by Dr-Noob** [comment]
After some quite busy weeks, I have managed to schedule some time for this. I have pushed a commit that should fix most of the detection issues reported here. Can you guys give it a try? @mdoksa76 @exkc 

I have not included all known SIDs, only those that you reported - I will include all when we know that this method works.

Also, @mdoksa76, you said your Orange Pi zero LTS is an H2+ but looking at several pages (e.g., http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero-LTS.html) they say this should actually be an H3 chip.

**Comment by mdoksa76** [comment]
[image: IMG_20230311_124952.jpg]

sub, 11. ožu 2023. u 12:07 Dr-Noob ***@***.***> napisao je:

**Comment by mdoksa76** [comment]
![cpufetch-h3](https://user-images.githubusercontent.com/122205220/224484459-805ffac9-92bb-47d3-8567-64e7fdc70d9a.png)

**Comment by Dr-Noob** [comment]
Looking good!

So this one that is detected as an H3, is actually an H3 or is it another SoC? Also, the first picture is not showing for me.

**Comment by mdoksa76** [comment]
![IMG_20230311_124952](https://user-images.githubusercontent.com/122205220/224489021-3a8eddff-08ab-4ba1-8ea7-314ce621996f.jpg)

**Comment by mdoksa76** [comment]
H2+ is H3 with 100 MHz lower turbo frequency. You can see on orange pi page for Zero LTS both chips H3 and H2+ on pictures, but in Hardware specifications table is only info about H3.

**Comment by Dr-Noob** [comment]
That makes totally sense since it also matches what the [linux-sunxi](https://linux-sunxi.org/SID_Register_Guide#Currently_known_SID.27s) page says. I have fixed it, now it should report H2+ for your Orange Pi zero LTS. By the way, do you have any other Allwinner to test, @mdoksa76?

**Comment by mdoksa76** [comment]
Orange Pi Lite is H3, Orange PI Lite 2 is H6, Orange Pi Zero 2 is H616. I will try them and report.

**Comment by mdoksa76** [comment]
Orange Pi Lite (H3)
![opi-lite-h3](https://user-images.githubusercontent.com/122205220/224496975-7443bd8f-b269-4746-9f4a-6c64cc567dd4.png)

**Comment by mdoksa76** [comment]
Orange Pi Lite 2 (H6)
![opi-lite2-h6](https://user-images.githubusercontent.com/122205220/224503051-a6b3f970-9184-41ac-b8d0-e29da4014b45.png)

**Comment by mdoksa76** [comment]
Orange Pi Zero LTS (H2+)
![opi-zero-lts-h2+](https://user-images.githubusercontent.com/122205220/224503082-73b1cd10-bc99-4684-ac48-746d83a5f817.png)

**Comment by mdoksa76** [comment]
Orange Pi Zero 2 (H616)
![opi-zero2-h616](https://user-images.githubusercontent.com/122205220/224513371-64e83b7c-86de-433e-9b24-8b7590253f01.png)

**Comment by Dr-Noob** [comment]
What an excellent feedback! I have pushed a new commit. So:
- Orange Pi Lite (H3): Seems like you executed an old cpufetch version? If not, can you download again and run and paste `cpufetch -V` and `cpufetch -v`?
- Orange Pi Lite 2 (H6): Should work now.
- Orange Pi Zero LTS (H2+): Awesome.
- Orange Pi Zero 2 (H616): Should work now.

**Comment by mdoksa76** [comment]
Irange Pi Lite 2 - H6
![opi-lite2-h6](https://user-images.githubusercontent.com/122205220/224761511-95aca18e-2ca4-4860-beb0-36abe59329c4.png)

**Comment by mdoksa76** [comment]
Orange Pi Lite - H3 - still not showing H3
![opi-lite-h3](https://user-images.githubusercontent.com/122205220/224761967-dce29e41-d256-4ef7-9747-17f05e22bd3d.png)

**Comment by Dr-Noob** [comment]
> Orange Pi Lite - H3 - still not showing H3 ![opi-lite-h3](https://user-images.githubusercontent.com/122205220/224761967-dce29e41-d256-4ef7-9747-17f05e22bd3d.png)

I suspect that it is caused because cpufetch is unable to find the SID. Can you run `cpufetch -v` (lower case, not upper case V)? 

Also, if it does not find it, can you check under `/sys/bus/nvmem/devices` to see if SID is available in any other file?

**Comment by mdoksa76** [comment]
There is no /sys/bus/nvmem/
![opi-lite](https://user-images.githubusercontent.com/122205220/226164506-c3c93c84-2dbe-4e0f-a392-75a8412da0cf.png)
devices

**Comment by Dr-Noob** [comment]
If there is no `/sys/bus/nvmem/devices/sunxi-sid0/nvmem`, it is expected that cpufetch is unable to find the exact SoC model when the chip is an sun8i. However, I was thinking that it the program actually knows that it is an allwinner, so why not showing at least the logo?

I have pushed a new commit. It should print "Unknown" in the SoC model, but print the Allwinner logo.

**Comment by Dr-Noob** [comment]
Also, this is a bit out of topic but still exciting - I just found out that /sys/bus/nvmem/devices/*/nvmem may contain valuable information on non-Allwinner chips too!

I have a rockchip ARM CPU which cpufetch has always been unable to properly detect, but it actually has a nvmem file that probably contains valuable information to determine the exact chip...

**Comment by Dr-Noob** [comment]
@mdoksa76 @exkc I hope you will appreciate [this acknowledgment](https://github.com/Dr-Noob/cpufetch#7-acknowledgements) for your excellent support throughout this thread!
