### ISSUE TITLE
Failed to detect some CPU values

### ISSUE THREAD

**Issue by edufe** [Dr-Noob/cpufetch#51]
This is the output of the command:

╭─eduardo@charles ~/cpufetch  ‹master›
╰─$ cpufetch
open: No such file or directory
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: SMT level was not found when querying topology

                                                              Name:              Pentium(R) Dual-Core CPU E5700 @ 3.00GHz
                                                              Microarchitecture: Penryn
                                                              Technology:        45nm
                                                              Max Frequency:     Unknown
                                                              Cores:             0 cores
                                                              AVX:               No
                                                              FMA:               No
                                                              L1i Size:          32KB
                                                              L1d Size:          32KB
                                                              L2 Size:           2MB
                                                              Peak Performance:  Unknown

╭─eduardo@charles ~/cpufetch  ‹master›
╰─$ cpufetch --debug
open: No such file or directory
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: SMT level was not found when querying topology
cpufetch v0.96 (x86_64 build)
Pentium(R) Dual-Core CPU E5700 @ 3.00GHz
- Max standard level: 0x0000000D
- Max extended level: 0x80000008
- CPUID dump: 0x0001067A
╭─eduardo@charles ~/cpufetch  ‹master›
╰─$

![image](https://user-images.githubusercontent.com/54588576/113724459-c05edc80-96c8-11eb-9090-5936e37fa5c5.png)

**Comment by Dr-Noob** [comment]
Whoops!

I am aware that I can't fix the frequency issue. We are tracking this problem in issue #50. However the issue about the number of cores looks like a mistake from my part. I've just pushed a commit to `bugfix2` branch. Please, move to that branch, try the new commit and paste the output here.

You should not get any error message, unknown frequency, and the right number of cores detected (two cores in this case).

Thanks!

**Comment by edufe** [comment]
Hi Dr, thanks for replying so fast...

I tried again but still not working properly. Maybe I did something wrong,
but heres is the output of what I did:

***@***.*** ~/cpufetch  ‹master›
> ╰─$ git pull
>
>
>   1 ↵
> remote: Enumerating objects: 10, done.
> remote: Counting objects: 100% (10/10), done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 10 (delta 6), reused 10 (delta 6), pack-reused 0
> Unpacking objects: 100% (10/10), 1.25 KiB | 27.00 KiB/s, done.
> From https://github.com/Dr-Noob/cpufetch
>    d56f7ff..ec2ad4f  master     -> origin/master
>  * [new branch]      bugfix2    -> origin/bugfix2
> Updating d56f7ff..ec2ad4f
> Fast-forward
>  src/common/udev.c | 16 +++++-----------
>  1 file changed, 5 insertions(+), 11 deletions(-)
> ***@***.*** ~/cpufetch  ‹master›
> ╰─$ git checkout bugfix2
> Branch 'bugfix2' set up to track remote branch 'bugfix2' from 'origin'.
> Switched to a new branch 'bugfix2'
> ***@***.*** ~/cpufetch  ‹bugfix2›
> ╰─$ make
> gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic
> -std=c99 -DARCH_X86 -Wfloat-equal -Wshadow -Wpointer-arith
> src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c
> src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c
> src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
> ***@***.*** ~/cpufetch  ‹bugfix2›
> ╰─$ ll
> total 120K
> -rwxrwxr-x 1 eduardo eduardo  87K abr  6 12:33 cpufetch
> -rw-rw-r-- 1 eduardo eduardo 2,1K abr  6 10:59 cpufetch.8
> drwxrwxr-x 2 eduardo eduardo 4,0K abr  6 10:59 doc
> -rw-rw-r-- 1 eduardo eduardo 1,1K abr  6 10:59 LICENSE
> -rw-rw-r-- 1 eduardo eduardo 1,9K abr  6 10:59 Makefile
> drwxrwxr-x 2 eduardo eduardo 4,0K abr  6 10:59 pictures
> -rw-rw-r-- 1 eduardo eduardo 4,8K abr  6 10:59 README.md
> drwxrwxr-x 5 eduardo eduardo 4,0K abr  6 10:59 src
> ***@***.*** ~/cpufetch  ‹bugfix2›
> ╰─$ ./cpufetch
> [ERROR]: SMT level was not found when querying topology
>
>
>
>
>
>                                                               Name:
>        Pentium(R) Dual-Core CPU E5700 @ 3.00GHz
>
> Microarchitecture: Penryn
>                                                               Technology:
>        45nm
>                                                               Max
> Frequency:     Unknown
>                                                               Cores:
>       0 cores
>                                                               AVX:
>       No
>                                                               FMA:
>       No
>                                                               L1i Size:
>        32KB
>                                                               L1d Size:
>        32KB
>                                                               L2 Size:
>       2MB
>                                                               Peak
> Performance:  Unknown
>
>
>
>
>
> ***@***.*** ~/cpufetch  ‹bugfix2›
> ╰─$
>

I'm sorry I haven't had time to go through the source code to help identify
the problem, maybe later...
I really like this project, as I am a fan of neofetch and this is a nice
utility to have.

Let me know if I can help you

Cheers !

**Comment by Dr-Noob** [comment]
Sorry, I was a bit in a hurry and made a silly mistake.

I've just pushed a new commit to `bugfix2`. Give it another go and let's see what happens.

**Comment by edufe** [comment]
Now it works!!!!

Thanks a lot, now it works !!!

You can see it here in action:
https://asciinema.org/a/AJ8ALLCinjdrHBJ16fegXO7cC

Thanks again for your time !

Eduardo.

**Comment by Dr-Noob** [comment]
Great! 

Thanks for reporting the bug, it looks like it is fixed now. I will merge the changes to master soon. 

Closing the issue.
